version: '3.6'
services:

  database:
    image: postgres:12
    container_name: aerpaw-db
    networks:
      - backend
    volumes:
      - ./pg_data/data:${PGDATA}
      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django
    container_name: aerpaw-portal
    depends_on:
      - database
    networks:
      - frontend
      - backend
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    environment:
      - UWSGI_UID=${UWSGI_UID}
      - UWSGI_GID=${UWSGI_GID}

  nginx:
    image: nginx:1
    container_name: aerpaw-nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    networks:
      - frontend
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS_DIR}:/etc/ssl:ro

networks:
  frontend:
  backend: